name: pytest

on:
  pull_request:
    branchs:
      - main
  push:
    branches:
      - main
      - dev

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [3.6, 3.7, 3.8, 3.9]
      steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: python set up ${{ matrix.python-versions }}
          uses: actions/setup-python@v1
        - name: install pytest and pytest-dotenv
          run: pip3 install pytest pytest-dotenv
        - name: run pytest
          run: python3 -m pytest tests